---
title: "Creating a map of the geographical distribution of the Eucalyptus phyloGWAS dataset (Adna and Exs)"
author: "Anne-Cecile Colin"
date: "15/06/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library('tidyverse')
library('ggrepel')
library('leaflet')
library('sf')
library('raster')
library('rgdal')
library('ggmap')
sites <- read.csv("../data/AC_species_functional_traits_latlongs_climate.csv")
```

```{r dataset, echo=FALSE}
summary(sites)
str(sites)
```

```{r Aus map}
m1 <- get_stamenmap( bbox = c(left = 110, bottom = -45, right = 160, top = -10),
zoom = 4, maptype = "terrain-background")
ggmap(m1) +
  geom_point(data = sites, aes(x=longitude,y=latitude,col=depth))
```

## Plotting species sampling points onto Australia's climate zones from the Aus' Bureau of Meteorology:

First, reading data and converting as a raster:
``` {r straya climate zones raster}
infile <- "../data/kpn/kpnall.txt"
data <- as.matrix(read.table(infile, skip = 6)) 
data[data == -9999] = NA
rr <- raster(data, crs = "+init=epsg:4326")
extent(rr) = c(112, 112+0.025*1681, -44, -44+0.025*1361)

rr
```

Then plotting the data:
``` {r plotting climate zones}
adm <- getData("GADM", country="AUS", level=1)
rr = mask(rr, adm)
plot(rr)
## come back to this stage and learn how to plot raster and points together with ggplot2 (look at thread in last tab)
gg

test_rr <- as(rr, "SpatialPixelsDataFrame")
test_rr <- as.data.frame(test_rr)
colnames(test_rr) <- c("layer", "x", "y")
str(test_rr)
```

``` {r plotting sampling points}
library(raster)
library(rgeos)
library(ggplot2)
library(ggthemes)

straya <- gSimplify(getData("GADM", country= "AUS", level=1), tol=0.001, TRUE)
straya <- fortify(straya)

st <- read.csv("../data/species_coordinates.csv")
st$color <- "violetred3"
st[st$section %in% c('Exsertaria'),]$color <- "skyblue4" 
view(st)
summary(st)

testplot <- ggplot() +
  geom_tile(data=test_rr, aes(x, y, layer))

testplot
gg <- ggplot() +
  geom_map(data=straya, map=straya, map_id = 1) + 
  geom_raster(data=test_rr, aes(x=x, y=y, fill=layer)) +
                    #aes(x=long, y=lat, map_id=id, group=group),
                    #fill=NA, color="black") +
  geom_point(data=st, aes(x=longitude, y=latitude, color = color), 
                      alpha=1, na.rm=TRUE) +
  scale_size(range=c(2,7)) +
  scale_color_identity() +
  labs(title= "Coordinate data of species sampling points across Australia's climate zones", 
                x="Longitude", y= "Latitude") +
  coord_map() +
  theme_map() +
  theme(title= element_text(hjust = 0.5, vjust=1, face="bold"))
gg

```

``` {r zoom on specific site}
xmin <- # long minus
xmax <- # long plus
ymin <- # lat minus
ymax <- # lat plus

m2 <- get_stamenmap(bbox = c(left = xmin,
                             bottom = ymin,
                             right = xmax,
                             top = ymax),
                    zoom = 8, maptype = "terrain")
ggmap(m2) +
  geom_point(data = sites,
             aes(x=longitude,y=latitude,col=series))
```

``` {r cleaner way to select sites}
xmin2 <- 149.07
xmax2 <- 149.18
ymin2 <- -35.31
ymax2 <- -35.25

sitesClose <- sites %>% dplyr::filter(longitude > xmin2,
                                      longitude < xmax2,
                                      latitude > ymin2,
                                      latitude < ymax2)
library(ggrepel)

ggmap(m4) +
  geom_point(data = sitesClose, aes(x=longitude,y=latitude,col=depth)) +
  geom_label_repel(data = sitesClose,
                   aes(x=longitude,
                       y=latitude,
                       col=depth,
                       label=species_name),
                   box.padding = 0.9)
```
